name: ${COMPOSE_PROJECT_NAME:-backend_daily}

x-app-common: &app-common
  image: ${APP_IMAGE:-backend-daily:local}
  build:
    context: .
  restart: unless-stopped
  env_file:
    - .env
  depends_on:
    - mongodb

services:
  app:
    <<: *app-common
    #      - redis
    ports:
      - "127.0.0.1:${APP_HOST_PORT:-8000}:8000"

  app_blue:
    <<: *app-common
    profiles: ["bluegreen"]
    ports:
      - "127.0.0.1:${APP_BLUE_HOST_PORT:-8004}:8000"

  app_green:
    <<: *app-common
    profiles: ["bluegreen"]
    ports:
      - "127.0.0.1:${APP_GREEN_HOST_PORT:-8005}:8000"

  mongodb:
    image: mongo:7
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: [ "redis-server", "--appendonly", "yes" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s
    volumes:
      - redis_data:/data

  worker:
    <<: *app-common
    container_name: checkin_worker
    command: arq src.worker.WorkerSettings
    depends_on:
      - redis
      - app # Đảm bảo container api được khởi động trước worker
    env_file:
      - .env

volumes:
  mongo_data:
  redis_data:

