server {
    listen 80;
    listen [::]:80;
    server_name workingapi.pls.edu.vn working.api.pls.edu.vn;
    client_max_body_size 200m;

    location = /redoc { return 404; }
    location = /redoc/ { return 404; }

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name workingapi.pls.edu.vn;
    http2 on;
    client_max_body_size 200m;

    ssl_certificate /etc/nginx/ssl/pls.edu.vn/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/pls.edu.vn/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location = /redoc { return 404; }
    location = /redoc/ { return 404; }

    location / {
        proxy_pass http://127.0.0.1:__APP_HOST_PORT__;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "";
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name working.api.pls.edu.vn;
    http2 on;
    client_max_body_size 200m;

    ssl_certificate /etc/letsencrypt/live/working.api.pls.edu.vn/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/working.api.pls.edu.vn/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location = /redoc { return 404; }
    location = /redoc/ { return 404; }

    location / {
        proxy_pass http://127.0.0.1:__APP_HOST_PORT__;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "";
    }
}
