from enum import StrEnum
class DocumentTypeEnum(StrEnum):
    BUG = 'BUG'
    DOCUMENT = 'DOCUMENT'
    TC = 'TC'
    QA = 'QA'
    CHECKLIST = 'CHECKLIST'
    TODO = 'TODO'
    MEETING_DOCUMENT = 'MEETING_DOCUMENT'
    MEETING_REPORT = 'MEETING_REPORT'
    MEETING_CONTENT='MEETING_CONTENT'